[server]
maxUploadSize = 5
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showErrorDetails = "none"

[theme]
primaryColor = "#1f6f8b"
